export const colourOptions = [
    { value: 'ocean', label: 'Ocean', color: '#00B8D9' },
    { value: 'blue', label: 'Blue', color: '#0052CC' },
    { value: 'purple', label: 'Purple', color: '#5243AA' },
    { value: 'red', label: 'Red', color: '#FF5630' },
    { value: 'orange', label: 'Orange', color: '#FF8B00' },
    { value: 'yellow', label: 'Yellow', color: '#FFC400' },
    { value: 'green', label: 'Green', color: '#36B37E' },
    { value: 'forest', label: 'Forest', color: '#00875A' },
    { value: 'slate', label: 'Slate', color: '#253858' },
    { value: 'silver', label: 'Silver', color: '#666666' },
];

export const flavourOptions = [
    { value: 'vanilla', label: 'Vanilla', rating: 'safe' },
    { value: 'chocolate', label: 'Chocolate', rating: 'good' },
    { value: 'strawberry', label: 'Strawberry', rating: 'wild' },
    { value: 'salted-caramel', label: 'Salted Caramel', rating: 'crazy' },
];

export const stateOptions = [
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AS', label: 'American Samoa' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'DC', label: 'District Of Columbia' },
    { value: 'FM', label: 'Federated States Of Micronesia' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'GU', label: 'Guam' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MH', label: 'Marshall Islands' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'MP', label: 'Northern Mariana Islands' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PW', label: 'Palau' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'PR', label: 'Puerto Rico' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VI', label: 'Virgin Islands' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' },
];

export const optionLength = [
    { value: 1, label: 'general' },
    {
        value: 2,
        label:
            'Evil is the moment when I lack the strength to be true to the Good that compels me.',
    },
    {
        value: 3,
        label:
            "It is now an easy matter to spell out the ethic of a truth: 'Do all that you can to persevere in that which exceeds your perseverance. Persevere in the interruption. Seize in your being that which has seized and broken you.",
    },
];

export const dogOptions = [
    { id: 1, label: 'Chihuahua' },
    { id: 2, label: 'Bulldog' },
    { id: 3, label: 'Dachshund' },
    { id: 4, label: 'Akita' },
];

export const groupedOptions = [
    {
        label: 'Colours',
        options: colourOptions,
    },
    {
        label: 'Flavours',
        options: flavourOptions,
    },
];


export const cities = [
    "cairo",
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "San Francisco",
    "Indianapolis",
    "Columbus",
    "Fort Worth",
    "Charlotte",
    "Memphis",
    "Boston",
    "Baltimore",
    "Detroit",
    "El Paso",
    "Seattle",
    "Denver",
    "Washington D.C.",
    "Nashville",
    "Portland",
    "Oklahoma City",
    "Las Vegas",
    "Louisville",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Long Beach",
    "Mesa",
    "Atlanta",
    "Colorado Springs",
    "Virginia Beach",
    "Raleigh",
    "Omaha",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Wichita",
    "New Orleans",
    "Arlington",
    "Cleveland",
    "Tampa",
    "Aurora",
    "Bakersfield",
    "St. Louis",
    "Riverside",
    "Anchorage",
    "Stockton",
    "Cincinnati",
    "Pittsburgh",
    "Toledo",
    "Greensboro",
    "Plano",
    "Hartford",
    "St. Paul",
    "Chandler",
    "Irvine",
    "Orlando",
    "Durham",
    "Richmond",
    "Des Moines",
    "Boise",
    "Providence",
    "Fort Lauderdale",
    "Tempe",
    "Birmingham",
    "Spokane",
    "Rochester",
    "Akron",
    "Fayetteville",
    "Tallahassee",
    "Shreveport",
    "Winston-Salem",
    "Scranton",
    "Augusta",
    "Mobile",
    "Huntsville",
    "Little Rock",
    "Knoxville",
    "Chattanooga",
    "Clarksville",
    "Montgomery",
    "Savannah",
    "Lubbock",
    "Lafayette",
    "Baton Rouge",
    "Eugene",
    "Springfield",
    "Pueblo",
    "Peoria",
    "Fresno",
    "Syracuse",
    "Worcester",
    "Newport News",
    "Hialeah",
    "Torrance",
    "Joliet",
    "Paterson",
    "Hampton",
    "McAllen",
    "Warren",
    "Sterling Heights",
    "West Valley City",
    "Columbia",
    "Overland Park",
    "Kansas City",
    "St. Petersburg",
    "Lancaster",
    "Palmdale",
    "Hayward",
    "Pomona",
    "Corpus Christi",
    "Amarillo",
    "Wilmington",
    "Fort Collins",
    "Arvada",
    "Ventura",
    "Rancho Cucamonga",
    "Ontario",
    "Oxnard",
    "Fullerton",
    "Norman",
    "Broken Arrow",
    "Columbus",
    "Fort Wayne",
    "Chesapeake",
    "Escondido",
    "Salem",
    "Carrollton",
    "Midland",
    "Denton",
    "Wichita Falls",
    "Gainesville",
    "Thornton",
    "Roseville",
    "Visalia",
    "Olathe",
    "Clarksville",
    "Abilene",
    "Fayetteville",
    "Killeen",
    "McKinney",
    "Mesquite",
    "Pasadena",
    "Orange",
    "Dayton",
    "Savannah",
    "Pembroke Pines",
    "Tallahassee",
    "Hollywood",
    "Lakeland",
    "Pompano Beach",
    "West Palm Beach",
    "Fort Lauderdale",
    "Tampa",
    "St. Petersburg",
    "Orlando",
    "Jacksonville",
    "Miami",
    "Tucson",
    "Mesa",
    "Chandler",
    "Glendale",
    "Scottsdale",
    "Gilbert",
    "Tempe",
    "Peoria",
    "Surprise",
    "Fresno",
    "Sacramento",
    "Oakland",
    "San Jose",
    "San Francisco",
    "San Diego",
    "Los Angeles",
    "Long Beach",
    "Oceanside",
    "Elk Grove",
    "Chico",
    "Eureka",
    "Costa Mesa",
    "Midland",
    "Petaluma",
    "Cape Coral",
    "Victoria",
    "Columbia",
    "Athens",
    "Fairfield",
    "Columbia",
    "Eugene",
    "Reno",
    "Coral Springs",
    "Amarillo",
    "Albuquerque",
    "Pensacola",
    "Kaneohe",
    "Naperville",
    "Champaign",
    "Tallahassee",
    "Overland Park",
    "Springfield",
    "Anaheim",
    "Fort Collins",
    "El Monte",
    "Kalamazoo",
    "Wilmington",
    "Newark",
    "Fontana",
    "Irving",
    "Cary",
    "Palmdale",
    "Warren",
    "Davenport",
    "Glens Falls",
    "Peoria",
    "Sioux City",
    "Green Bay",
    "Madison",
    "New London",
    "Greenville",
    "Greenwood",
    "Clinton",
    "Kingsport",
    "Tallahassee",
    "New Bern",
    "Clemson",
    "Elmira",
    "Kingsville",
    "Richmond",
    "Amarillo",
    "Galveston",
    "College Station",
    "Rochester",
    "Arlington",
    "Aurora",
    "Gresham",
    "Portsmouth",
    "San Antonio",
    "Killeen",
    "Downey",
    "Philadelphia",
    "Athens",
    "Midland",
    "Raleigh",
    "New York City",
    "Reno",
    "Miami",
    "Chattanooga",
    "Orlando",
    "Riverside",
    "Milwaukee",
    "New Haven",
    "Nashville",
    "Norfolk",
    "Minneapolis",
    "Kansas City",
    "Phoenix",
    "Albuquerque",
    "Atlanta",
    "Pittsburgh",
    "Winston-Salem",
    "Pittsburgh",
    "Chicago",
    "Seattle",
    "Omaha",
    "Washington",
    "Palo Alto",
    "Lubbock",
    "Gary",
    "Dover",
    "Plymouth",
    "Jackson",
    "Columbus",
    "Oxnard",
    "Port St. Lucie",
    "Longview",
    "Lincoln",
    "Champaign",
    "Norwich",
    "Mankato",
    "Springfield",
    "Jersey City",
    "Torrance",
    "Stockton",
    "Marietta",
    "Aurora",
    "Naperville",
    "Chico",
    "Tulsa",
    "Chico",
    "Alameda",
    "Killeen",
    "Toledo",
    "Columbus",
    "Tuscaloosa",
    "Vero Beach",
    "Auburn",
    "Modesto",
    "San Angelo",
    "Arkansas City",
    "Downey",
    "Alexandria",
    "Aurora",
    "Gresham",
    "Palatine",
    "Terre Haute",
    "Champaign",
    "Dallas",
    "Edison",
    "Newport News",
    "Niagara Falls",
    "Altoona",
    "Denton",
    "Edison",
    "Meridian",
    "New London",
    "Albany",
    "Kearney",
    "Gastonia",
    "Greenville",
    "Goldsboro",
    "New Castle",]